spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/uptimepulse_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:25}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:UptimePulseSuperSecureSecretKeyThatIsAtLeast512BitsLongForProductionHMACSHA512SecurityTokenGeneration!}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    org.springframework: INFO
    com.uptimepulse: DEBUG
